version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: phonebook-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: PhoneBookDb
    ports:
      - "5432:5432"
    volumes:
      - phonebook_pgdata:/var/lib/postgresql/data

volumes:
  phonebook_pgdata:
